"""Generate skill/scripts/spd_lint.py from src/padkit/{spd,lint}.py.

The Skill must lint without padkit installed, but the rules must not be
maintained twice. This bundles the two stdlib-only modules into one script;
tests/test_skill.py fails when the bundle is stale.

    uv run python scripts/build_skill_lint.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "padkit"
OUT = ROOT / "skill" / "scripts" / "spd_lint.py"

HEADER = '''#!/usr/bin/env python3
"""Standalone SPD linter for the spd Skill (stdlib only).

GENERATED by scripts/build_skill_lint.py from src/padkit/spd.py and lint.py.
Do not edit by hand.

    python3 spd_lint.py FILE.spd [--strict] [--json]
    python3 spd_lint.py FILE.spd --fix-indent   # print with spaces turned into tabs

Exit status: 0 clean, 1 errors (or warnings with --strict).
The padtools_ts AST cross-check (E900) needs the full padkit CLI.
"""

from __future__ import annotations
'''

FOOTER = '''

def main(argv: list[str] | None = None) -> int:
    import argparse
    import json

    ap = argparse.ArgumentParser(description="SPD linter")
    ap.add_argument("file")
    ap.add_argument("--strict", action="store_true")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--fix-indent", action="store_true")
    a = ap.parse_args(argv)
    src = open(a.file, encoding="utf-8").read() if a.file != "-" else __import__("sys").stdin.read()
    if a.fix_indent:
        print(fix_indent(src)[0], end="")
        return 0
    res = lint_text(src, a.file)
    if a.json:
        print(json.dumps({
            "path": a.file,
            "ok": not res.failed(a.strict),
            "stats": res.stats,
            "diagnostics": [d.to_dict() for d in res.diagnostics],
        }, ensure_ascii=False, indent=2))
    else:
        text = format_text(res)
        if text:
            print(text)
        print(format_summary(res))
    return 1 if res.failed(a.strict) else 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _body(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    text = re.sub(r'\A""".*?"""\n', "", text, flags=re.S)  # module docstring
    text = re.sub(r"^from __future__ import annotations\n", "", text, flags=re.M)
    text = re.sub(r"^from \.\w+ import \(.*?\)\n", "", text, flags=re.M | re.S)
    text = re.sub(r"^from \.\w+ import .*\n", "", text, flags=re.M)
    return text.strip("\n")


def build() -> str:
    parts = [HEADER]
    for name in ("spd.py", "lint.py"):
        parts.append(f"\n# ---- {name} " + "-" * (70 - len(name)) + "\n\n" + _body(SRC / name))
    return "\n".join(parts) + "\n" + FOOTER


if __name__ == "__main__":
    OUT.write_text(build(), encoding="utf-8")
    OUT.chmod(0o755)
    print(f"wrote {OUT.relative_to(ROOT)}", file=sys.stderr)
